name: CI NodeJS React

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install & Test Backend
      - name: Build & Test NodeJS
        run: |
          cd NodeJS/app
          npm install
          npm test

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & Push Backend Image
      - name: Build & Push NodeJS Image
        run: |
          docker build -t $DOCKER_USERNAME/node-app ./E-LearningBackend
          docker push $DOCKER_USERNAME/node-app

      # Build & Push Frontend Image
      - name: Build & Push React Image
        run: |
          docker build -t $DOCKER_USERNAME/react-app ./E-LearningFrontend
          docker push $DOCKER_USERNAME/react-app