name: CI NodeJS React

# Controls when the workflow will run
on:
  # Trigger on push to main branch
  push:
    branches:
      - main
env:
 DOCKER_USERNAME : ${{ vars.DOCKERHUB_USERNAME }}
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build & test NodeJS
        run: |
         cd NodeJS/app
         npm install
         npm test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build image NodeJS
        run: |
         docker build -t $DOCKER_USERNAME/node-app . /E-LearningBackend
         docker push $DOCKER_USERNAME/node-app

      - name: build image Angular
        run: |
         docker build -t $DOCKER_USERNAME/React-app . /E-LearningFrontend
         docker push $DOCKER_USERNAME/React-app
      - name: run docker compose
        run: |
        docker compose down
        docker compose up -d 